### ISSUE TITLE
Issue with yii 2.0.14

### ISSUE THREAD

**Issue by simonevallana** [yii2tech/ar-role#12] opened 2018-02-28 07:49 UTC
Enh #13618 in yii2 2.0.14 breaks ar-role behavior

For example, in AfterInsert event I cannot reach role attributes anymore.

**Comment by klimov-paul** [comment] 2018-03-01 23:42
Confirmed.
This is most likely caused by https://github.com/yiisoft/yii2/pull/13618

**Comment by klimov-paul** [comment] 2018-03-01 23:44
Issue affects only owner-master roles.
The roles where owner is a slave are saved correctly.

**Comment by klimov-paul** [comment] 2018-03-02 00:31
Resolved by commit e29dbf0b89e3598ed4e32331bb87a6f8dd9835b6

**Closed as completed by klimov-paul** 2018-03-02 00:31 UTC
Labels: bug
